info:
  component: Itau Api
  project:
    name: Itau-api
    version: 0.0.1-SNAPSHOT

server:
  port: 8077
  contextPath: /itau-api
  tomcat:
    basedir: /tmp/tomcat

management:
  security:
    enabled: false

spring:
  application:
    name: Itau-api
    h2:
      console:
        path: /h2

  jackson:
    default-property-inclusion: non_null

  jpa:
    show-sql: true
    format-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  logging:
  level:
    org:
      hibernate:
        type: trace

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:itau
    username: sa
    password:

    tomcat:
      max-wait: 60000
      initial-size: 10
      max-active: 150
      test-on-borrow: true